### ISSUE TITLE
error using py_rmpe_server

### ISSUE THREAD

**Issue by Minotaur-CN** [anatolix/keras_Realtime_Multi-Person_Pose_Estimation#1]
Dear anatolix,

some error when using your git code to generate data! 
python rmpe_server.py

---------------------------------------
   self._target(*self._args, **self._kwargs)
  File "rmpe_server.py", line 69, in loop
    headers = self.produce_headers(image, mask, labels, keypoints)
  File "rmpe_server.py", line 87, in produce_headers
    return headers
NameError: name 'headers' is not defined
-------------------------------------

and the  ./py_rmpe_server.py  in your READMD. seemed outdated according to your code!

**Comment by anatolix** [comment]
fixed. documentation updated.

nb: you don't really need to run ./rmpe_server.py at all(sorry because of this I've missed his stupid bug), @michalfaber made external server to run augmentation on separate machine. Since it is faster i've returned it inside train_pose in iterator form. 
updated doc about how to enable external server back if you want.

**Comment by Minotaur-CN** [comment]
Great!
Thanks for your update!
