### ISSUE TITLE
performance of training speed not well

### ISSUE THREAD

**Issue by Minotaur-CN** [anatolix/keras_Realtime_Multi-Person_Pose_Estimation#3]
Dear anatolix,
I use 5 gpus to train, but the GPU always keeps to 20% for 4GPU, It seems the GPU not runing on full speed.

**Comment by anatolix** [comment]
There are 2 possibilities:

1) this function in Keras works not very well yet, it was added less than month ago.
Looks like it has contention on passing data in and out card to cpu and back.
we pass 46*46*57*4*20 = 9.2Mb for each batch of 20 may be it is too much data, and for classification with 10 classes it is good function.

I take a look into it later but since i have not too much cards it is not a priority for me yet.

If you have card interconnect installed, you could try to patch Keras to make aggregation on one of the cards, change '/cpu:0' for '/gpu:0' may be it will be faster
https://github.com/fchollet/keras/blob/master/keras/utils/training_utils.py
And start from 2 cards not 5, they share PCI-E.

2) this is slowness of data preparation, it works well in my machine but you could test it on yours, may be it is slow for some reasons(disk, opencv without optimizations) or may be 5 cards is too many. 

How to test:
0) cd py_rmpe_server
1) start **rmpe_server.py** in one terminal
2) start **rmpe_server_tester.py raw** in second

in tester output you will see some like this
2637 **101.64079304019138** (3, 368, 368) (46, 46) (57, 46, 46)
2638 **101.64944106270283** (3, 368, 368) (46, 46) (57, 46, 46)
2639 **101.63348867225085** (3, 368, 368) (46, 46) (57, 46, 46)
93 is number of images per second. 

On server side you will see something like this
Val [2587/2645] aug **7.95 ms** (125.75 im/s), send **0.00 ms**
Val [2588/2645] aug 7.76 ms (128.85 im/s), send 0.00 ms
Val [2589/2645] aug 7.67 ms (130.31 im/s), send 0.00 ms

nb: tester writes average time per image since beginning, server writes time for last image. Cause of difference in times probably zero MQ speed.

this is speed of augmentation, in this case I have send time **0.00 ms** because I sending it to the tester, it does nothing with images it never waits and sending time is zero. Check this time against train_pose.py in if it has 0 there his means data augmentation is bottleneck (usually it looks like 19/20 times are zero, and once per batch is waits some time)

If augmentation is the bottleneck there is possible to run several augmentation servers, I will patch client/server if you need it, it is 5-10 lines of code

**Comment by Minotaur-CN** [comment]
Hi anatolix ,@anatolix 

-----------------------------------------

Val Side:
3046 73.51815281239382 (3, 368, 368) (46, 46) (57, 46, 46)
3047 73.52256930827204 (3, 368, 368) (46, 46) (57, 46, 46)
3048 73.52773278988396 (3, 368, 368) (46, 46) (57, 46, 46)
3049 73.52114092715587 (3, 368, 368) (46, 46) (57, 46, 46)
3050 73.5270661977841 (3, 368, 368) (46, 46) (57, 46, 46)
3051 73.5320086936882 (3, 368, 368) (46, 46) (57, 46, 46)
Server Side:
Val [3045/2645] aug 9.97 ms (100.30 im/s), send 0.00 ms
Val [3046/2645] aug 12.28 ms (81.44 im/s), send 0.00 ms
Val [3047/2645] aug 10.61 ms (94.29 im/s), send 0.00 ms
Val [3048/2645] aug 10.15 ms (98.52 im/s), send 0.00 ms
Val [3049/2645] aug 16.82 ms (59.46 im/s), send 0.00 ms
Val [3050/2645] aug 9.71 ms (102.97 im/s), send 0.00 ms
Val [3051/2645] aug 10.34 ms (96.73 im/s), send 0.00 ms

**Comment by anatolix** [comment]
It should be enough to feed approx 4 gpu. I.e bottleneck is keras implementation of multigpu training.
